export const countryCallCode = [
	{ name: "Afganistan", code: "+93" },
	{ name: "Afrika Selatan", code: "+27" },
	{ name: "Afrika Tengah", code: "+236" },
	{ name: "Albania", code: "+355" },
	{ name: "Algeria (Aljazair)", code: "+213" },
	{ name: "Amerika Serikat", code: "+1" },
	{ name: "Andorra", code: "+376" },
	{ name: "Angola", code: "+244" },
	{ name: "Antigua & Barbuda", code: "+267" },
	{ name: "Arab Saudi", code: "+966" },
	{ name: "Argentina", code: "+54" },
	{ name: "Armenia", code: "+374" },
	{ name: "Australia", code: "+61" },
	{ name: "Austria", code: "+43" },
	{ name: "Azerbaijan", code: "+994" },
	{ name: "Bahama", code: "+241" },
	{ name: "Bahrain", code: "+973" },
	{ name: "Bangladesh", code: "+880" },
	{ name: "Barbados", code: "+245" },
	{ name: "Belanda", code: "+31" },
	{ name: "Belarus", code: "+375" },
	{ name: "Belgia", code: "+32" },
	{ name: "Belize", code: "+501" },
	{ name: "Benin", code: "+229" },
	{ name: "Bhutan", code: "+975" },
	{ name: "Bolivia", code: "+591" },
	{ name: "Bosnia & Herzegovina", code: "+387" },
	{ name: "Botswana", code: "+267" },
	{ name: "Brasil", code: "+55" },
	{ name: "Britania Raya (Inggris)", code: "+44" },
	{ name: "Brunei Darussalam", code: "+673" },
	{ name: "Bulgaria", code: "+359" },
	{ name: "Burkina Faso", code: "+226" },
	{ name: "Burundi", code: "+257" },
	{ name: "Ceko", code: "+420" },
	{ name: "Chad", code: "+235" },
	{ name: "Chili", code: "+56" },
	{ name: "China", code: "+86" },
	{ name: "Denmark", code: "+45" },
	{ name: "Djibouti", code: "+253" },
	{ name: "Domikia", code: "+766" },
	{ name: "Ekuador", code: "+593" },
	{ name: "El Salvador", code: "+503" },
	{ name: "Eritrea", code: "+291" },
	{ name: "Estonia", code: "+372" },
	{ name: "Ethiopia", code: "+251" },
	{ name: "Fiji", code: "+679" },
	{ name: "Filipina", code: "+63" },
	{ name: "Finlandia", code: "+358" },
	{ name: "Gabon", code: "+241" },
	{ name: "Gambia", code: "+220" },
	{ name: "Georgia", code: "+995" },
	{ name: "Ghana", code: "+233" },
	{ name: "Grenada", code: "+472" },
	{ name: "Guatemala", code: "+502" },
	{ name: "Guinea", code: "+224" },
	{ name: "Guinea Bissau", code: "+245" },
	{ name: "Guinea Khatulistiwa", code: "+240" },
	{ name: "Guyana", code: "+592" },
	{ name: "Haiti", code: "+509" },
	{ name: "Honduras", code: "+504" },
	{ name: "Hongaria", code: "+36" },
	{ name: "Hongkong", code: "+852" },
	{ name: "India", code: "+91" },
	{ name: "Indonesia", code: "+62" },
	{ name: "Irak", code: "+964" },
	{ name: "Iran", code: "+98" },
	{ name: "Irlandia", code: "+353" },
	{ name: "Islandia", code: "+354" },
	{ name: "Israel", code: "+972" },
	{ name: "Italia", code: "+39" },
	{ name: "Jamaika", code: "+875" },
	{ name: "Jepang", code: "+81" },
	{ name: "Jerman", code: "+49" },
	{ name: "Jordan", code: "+962" },
	{ name: "Kamboja", code: "+855" },
	{ name: "Kamerun", code: "+237" },
	{ name: "Kanada", code: "+1" },
	{ name: "Kazakhstan", code: "+7" },
	{ name: "Kenya", code: "+254" },
	{ name: "Kirgizstan", code: "+996" },
	{ name: "Kiribati", code: "+686" },
	{ name: "Kolombia", code: "+57" },
	{ name: "Komoro", code: "+269" },
	{ name: "Republik Kongo", code: "+243" },
	{ name: "Korea Selatan", code: "+82" },
	{ name: "Korea Utara", code: "+850" },
	{ name: "Kosta Rika", code: "+506" },
	{ name: "Kroasia", code: "+385" },
	{ name: "Kuba", code: "+53" },
	{ name: "Kuwait", code: "+965" },
	{ name: "Laos", code: "+856" },
	{ name: "Latvia", code: "+371" },
	{ name: "Lebanon", code: "+961" },
	{ name: "Lesotho", code: "+266" },
	{ name: "Liberia", code: "+231" },
	{ name: "Libya", code: "+218" },
	{ name: "Liechtenstein", code: "+423" },
	{ name: "Lituania", code: "+370" },
	{ name: "Luksemburg", code: "+352" },
	{ name: "Madagaskar", code: "+261" },
	{ name: "Makao", code: "+853" },
	{ name: "Makedonia", code: "+389" },
	{ name: "Maladewa", code: "+960" },
	{ name: "Malawi", code: "+265" },
	{ name: "Malaysia", code: "+60" },
	{ name: "Mali", code: "+223" },
	{ name: "Malta", code: "+356" },
	{ name: "Maroko", code: "+212" },
	{ name: "Marshall (Kep.)", code: "+692" },
	{ name: "Mauritania", code: "+222" },
	{ name: "Mauritius", code: "+230" },
	{ name: "Meksiko", code: "+52" },
	{ name: "Mesir", code: "+20" },
	{ name: "Mikronesia (Kep.)", code: "+691" },
	{ name: "Moldova", code: "+373" },
	{ name: "Monako", code: "+377" },
	{ name: "Mongolia", code: "+976" },
	{ name: "Montenegro", code: "+382" },
	{ name: "Mozambik", code: "+258" },
	{ name: "Myanmar", code: "+95" },
	{ name: "Namibia", code: "+264" },
	{ name: "Nauru", code: "+674" },
	{ name: "Nepal", code: "+977" },
	{ name: "Niger", code: "+227" },
	{ name: "Nigeria", code: "+234" },
	{ name: "Nikaragua", code: "+505" },
	{ name: "Norwegia", code: "+47" },
	{ name: "Oman", code: "+968" },
	{ name: "Pakistan", code: "+92" },
	{ name: "Palau", code: "+680" },
	{ name: "Panama", code: "+507" },
	{ name: "Pantai Gading", code: "+225" },
	{ name: "Papua Nugini", code: "+675" },
	{ name: "Paraguay", code: "+595" },
	{ name: "Perancis", code: "+33" },
	{ name: "Peru", code: "+51" },
	{ name: "Polandia", code: "+48" },
	{ name: "Portugal", code: "+351" },
	{ name: "Qatar", code: "+974" },
	{ name: "Rep. Dem. Kongo", code: "+242" },
	{ name: "Republik Dominika", code: "+2484" },
	{ name: "Rumania", code: "+40" },
	{ name: "Rusia", code: "+7" },
	{ name: "Rwanda", code: "+250" },
	{ name: "Saint Kitts and Nevis", code: "+868" },
	{ name: "Saint Lucia", code: "+757" },
	{ name: "Saint Vincent & the Grenadines", code: "+783" },
	{ name: "Samoa", code: "+685" },
	{ name: "San Marino", code: "+378" },
	{ name: "Sao Tome & Principe", code: "+239" },
	{ name: "Selandia Baru", code: "+64" },
	{ name: "Senegal", code: "+221" },
	{ name: "Serbia", code: "+381" },
	{ name: "Seychelles", code: "+248" },
	{ name: "Sierra Leone", code: "+232" },
	{ name: "Singapura", code: "+65" },
	{ name: "Siprus", code: "+357" },
	{ name: "Slovenia", code: "+386" },
	{ name: "Slowakia", code: "+421" },
	{ name: "Solomon (Kep.)", code: "+677" },
	{ name: "Somalia", code: "+252" },
	{ name: "Spanyol", code: "+34" },
	{ name: "Sri Lanka", code: "+94" },
	{ name: "Sudan", code: "+249" },
	{ name: "Sudan Selatan", code: "+211" },
	{ name: "Suriah", code: "+963" },
	{ name: "Suriname", code: "+597" },
	{ name: "Swaziland", code: "+268" },
	{ name: "Swedia", code: "+46" },
	{ name: "Swiss", code: "+41" },
	{ name: "Tajikistan", code: "+992" },
	{ name: "Tanjung Verde", code: "+238" },
	{ name: "Tanzania", code: "+255" },
	{ name: "Taiwan", code: "+886" },
	{ name: "Thailand", code: "+66" },
	{ name: "Timor Leste", code: "+670" },
	{ name: "Togo", code: "+228" },
	{ name: "Tonga", code: "+676" },
	{ name: "Trinidad & Tobago", code: "+867" },
	{ name: "Tunisia", code: "+216" },
	{ name: "Turki", code: "+90" },
	{ name: "Turkmenistan", code: "+993" },
	{ name: "Tuvalu", code: "+688" },
	{ name: "Uganda", code: "+256" },
	{ name: "Ukraina", code: "+380" },
	{ name: "Uni Emirat Arab", code: "+971" },
	{ name: "Uruguay", code: "+598" },
	{ name: "Uzbekistan", code: "+998" },
	{ name: "Vanuatu", code: "+678" },
	{ name: "Venezuela", code: "+58" },
	{ name: "Vietnam", code: "+84" },
	{ name: "Yaman", code: "+967" },
	{ name: "Yunani", code: "+30" },
	{ name: "Zambia", code: "+260" },
	{ name: "Zimbabwe", code: "+263" },
];
