export const SETTOKEN = "SETTOKEN";
export const SETUSERSETTING = "SETUSERSETTING";
export const SETNOTIF = "SETNOTIF";
export const SETCOUNTMESSAGE = "SETCOUNTMESSAGE";
export const SETCOUNTMESSAGEGROUP = "SETCOUNTMESSAGEGROUP";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_SEARCH_EVENT_INPUT = "SET_SEARCH_EVENT_INPUT";
export const SET_SEARCH_DESTINATION_INPUT = "SET_SEARCH_DESTINATION_INPUT";
