require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'funtravia' do
    config = use_native_modules!
    pod 'GoogleSignIn', '~> 5.0.2'
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
    use_react_native!(:path => config["reactNativePath"])
    target 'funtraviaTests' do
        inherit! :complete
        # Pods for testing
    end

    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    # use_flipper!
    use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
    post_install do |installer|
        flipper_post_install(installer)
    end
    end

    target 'funtravia-tvOS' do
    # Pods for funtravia-tvOS

    target 'funtravia-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
